
version: '3'

services:
  web:
    build: .
    command: ./entrypoint.sh
    volumes:
      - ./IGS-Software-Manager:/app
      - ./IGS-Software-Manager/db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
